name: stock-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - pandas
  - numpy
  - scikit-learn
  - python-dotenv
  - pytest
  - pip
  - pip:
      - yfinance
      - python-multipart
